// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    // Gunakan array untuk menampung semua token Origin Trial
    'origin-trial': [
      // Token untuk Writer API (dari file asli kamu)
      'Atqb/wGDlBk1i8ORWTVZgqa0NxvigKUZiX+zF7OTUa3vwoDkuZr/L2OvCYzlDLN8RMEs3zlX+SFtmt/2KdDlrAsAAABOeyJvcmlnaW4iOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJmZWF0dXJlIjoiQUlXcml0ZXJBUEkiLCJleHBpcnkiOjE3Njk0NzIwMDB9', 
      
      // Token untuk Proofreader API (dari prompt terbaru kamu)
      'AoBrNWZcn2CqtE1uE9nSbCjI+TBQLZN/PJJxNwo9ToEhvaUl0Yoon2gb9W6B06R+s7DgE3Vpxeb/pF0DXZVmsAcAAABTeyJvcmlnaW4iOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJmZWF0dXJlIjoiQUlQcm9vZnJlYWRlckFQSSIsImV4cGlyeSI6MTc3OTE0ODgwMH0=',
      
      // Kamu bisa menambahkan token lainnya di sini
      // 'TOKEN_UNTUK_REWRITER_API_DI_SINI',
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Tag meta manual di sini sudah tidak diperlukan lagi.
          Next.js akan membuatkannya secara otomatis dari objek metadata di atas.
        */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}