import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    'origin-trial': 'Al3oZtCy4AH02dyGRpa2PXnluMxVYbVo9ugUkRXadwBoOiNnuRD6CR1USnpRFA/QHgWydwjBqMCDR80jJr8ufQ0AAAB3eyJvcmlnaW4iOiJodHRwczovL3N0dWR5LW1pbmQtbmluZS52ZXJjZWwuYXBwOjQ0MyIsImZlYXR1cmUiOiJBSVByb29mcmVhZGVyQVBJIiwiZXhwaXJ5IjoxNzc5MTQ4ODAwLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=' // Paste your token
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Alternative: Add as meta tag */}
        <meta httpEquiv="origin-trial" content="Al3oZtCy4AH02dyGRpa2PXnluMxVYbVo9ugUkRXadwBoOiNnuRD6CR1USnpRFA/QHgWydwjBqMCDR80jJr8ufQ0AAAB3eyJvcmlnaW4iOiJodHRwczovL3N0dWR5LW1pbmQtbmluZS52ZXJjZWwuYXBwOjQ0MyIsImZlYXR1cmUiOiJBSVByb29mcmVhZGVyQVBJIiwiZXhwaXJ5IjoxNzc5MTQ4ODAwLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
